### ISSUE TITLE
文件服务器启动参数少了一个

### ISSUE THREAD

**Issue by callmepeanut** [hanxi/md-pages#1]
文件服务器的启动参数应该加上路径：  python file-server.py ./files/ 8001
不然获取不到端口，默认为8000，会和HTTP服务器冲突
建议使用 -d, -p 等参数配置

**Comment by hanxi** [comment]
:+1: 文档已修改好了，至于使用 -d -p 我暂时没空修改，你可以修改好提个 pull request 到 https://github.com/hanxi/http-file-server
